### ISSUE TITLE
Shortcut keys does not work

### ISSUE THREAD

**Issue by shinjidf** [mokojm/townshell#3]
Hi mokojm, I'm sending the files as requested on Reddit.

1. My keyboard is QWERTY Brazilian ABNT2. It has some extra keys like "ç": http://kbdlayout.info/KBDBR/
2. Yes, QWERTY
3. "Space" key and "c" key. 

[kivy_21-04-26_6.txt](https://github.com/mokojm/townshell/files/6380329/kivy_21-04-26_6.txt)
[town.log](https://github.com/mokojm/townshell/files/6380338/town.log)
[town_old.log](https://github.com/mokojm/townshell/files/6380339/town_old.log)

**Comment by mokojm** [comment]
Thank you for feedback. There seems to be an issue with your configuration file townshell.cfg. If no personal information inside you can share it. Anyways, you can delete the file then restart Townshell. 
About the keyboard issue, I think you can ignore the WARNING in the console screen. I need to investigate deeper and try it on my computer. I'll keep you posted.

**Comment by shinjidf** [comment]
Sure. I renamed it as TXT to upload.
[townshell.txt](https://github.com/mokojm/townshell/files/6387473/townshell.txt)

**Comment by mokojm** [comment]
I managed to reproduce the bug. The fix is easy to implement but requires me to release a fix version for TownShell. All of this comes from the fact that TownShell was developped on a French keyboard which means the layout for shortcuts was different. So, if you absolutely want to use Townshell shortcuts while playing Townscaper, you could add French language to your Windows and then use 'alt+tab' to switch to french while in game.

Sorry for inconvenience, but thank you very much for highlighting this issue. I may use it as a chance to deliver some new features while fixing the bug.

**Comment by shinjidf** [comment]
Ok, I will wait for a new release.

**Comment by mokojm** [comment]
The new release is out :)

**Comment by shinjidf** [comment]
Got a new error
[town.log](https://github.com/mokojm/townshell/files/6443787/town.log)
[kivy_21-05-07_0.txt](https://github.com/mokojm/townshell/files/6443788/kivy_21-05-07_0.txt)
[townshell.txt](https://github.com/mokojm/townshell/files/6443789/townshell.txt)

**Comment by mokojm** [comment]
Thank you again for your feedback, There was a ',' missing on "ram_limit" line at the end. You can correct your 'townshell.cfg' or download again Townshell.exe from the same release the package has been updated. Sorry for the bad experience.

**Comment by shinjidf** [comment]
Thank you, now it's working!
